In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('train_data_clinical_patient.csv')
rna = pd.read_csv('train_data_rna-seq.csv')

In [2]:
test = pd.read_csv('test_data_rna-seq_v1.csv')
test = test.iloc[:,2:] # 전체 행 / 0,1 열 제외하고 출력
test = test.dropna(axis=0) # NaN값 제거
test = test.T # 행/열 변환
test = test.rename(lambda label:label[8:]) #patient_제외하고 레이블링 설정
test['sort'] = test.index #맨 마지막 열에 sort열 생성
test = test.astype(np.float64)
test = test.sort_values(by='sort',ascending=True) #인덱스 정렬
test = test.drop(columns='sort') # sort 열 제거

In [3]:
test #74 rows * 16328columns

1       2       3       4       6       11      12      19      20     \
1  -3.6531 -1.2866 -0.8844  1.0053 -2.1361 -1.3499 -2.6803 -0.8835 -2.0407   
2   0.2661  0.6528 -0.7820  0.6400 -0.3290 -1.1215  2.0988  0.9483 -0.1546   
3   0.6270  0.0497  0.2196 -0.1943  0.1297 -1.0722  0.0220  0.3827  1.2503   
4   1.8635  1.2665  0.1321 -0.4352  0.1718  0.3453  0.5043  1.5079  1.5333   
5  -0.6275 -0.6568 -1.6290 -1.4820 -1.7779 -0.9692 -1.5749 -0.4975 -1.8058   
..     ...     ...     ...     ...     ...     ...     ...     ...     ...   
70 -2.2865 -2.6079 -0.3615  1.0572 -0.6241 -0.1795  0.7696 -0.6364 -0.0445   
71  1.8908  1.6385  1.3709  1.2346  2.3879  1.7848 -0.6311 -1.4158  0.5490   
72 -3.1094 -0.4106 -0.2267 -0.5026 -0.4874 -1.6739 -1.2181 -0.3655 -1.0931   
73 -2.2865 -0.9103 -3.6377  0.1517 -2.0793 -1.3053 -2.8440 -3.2393 -0.0147   
74 -0.7116 -1.6548 -1.1031 -0.2450 -0.4768 -1.3053  0.0211 -0.5419 -0.0954   

     22     ...   20521   20522   20523   20524   20525   20526   20527  \
1  -2.2589  ... -0.7690 -0.1299  0.1915 -0.1904 -1.1761  1.8149  0.7038   
2  -0.4375  ... -0.0649 -0.0885 -0.8805 -0.5958  0.5515  0.3507  0.3513   
3  -0.4797  ...  1.2754  1.3721  1.2591  1.9395  1.5085  1.7182  2.0320   
4   0.2684  ...  1.3948  1.0977  2.1222  0.8577  2.7827  0.4183  0.8452   
5   0.6240  ... -1.1046 -0.9107  0.4796  0.2064 -0.6044 -0.6893 -0.9811   
..     ...  ...     ...     ...     ...     ...     ...     ...     ...   
70  0.5093  ...  1.4717  1.9149 -1.2712 -0.5375 -1.5697 -0.4334 -0.7383   
71 -0.3936  ...  1.3178  0.9137 -0.8435  0.6213 -0.8221  1.9176  0.6194   
72  1.5220  ... -0.8721 -2.1572 -1.5062 -1.5347 -0.2171  0.5606 -0.7373   
73  2.0823  ... -2.2624 -0.7311 -1.5147 -1.2047 -2.3282 -0.1411 -0.7221   
74 -0.5216  ... -0.3875 -0.4860  0.2175  1.1372  0.1300 -0.3672  0.1264   

     20528   20529   20530  
1   1.1159 -0.3484 -0.4009  
2  -0.1165 -0.2731  0.0095  
3   0.1193  0.9679  1.0774  
4  -2.0517  1.1303  0.4846  
5   0.7733 -1.4425 -0.7750  
..     ...     ...     ...  
70  1.5243 -1.5691 -0.6089  
71  0.9272 -2.2363 -0.6841  
72 -0.3267 -1.3742  0.0142  
73  0.8746 -0.7372 -3.0246  
74  0.2018 -0.5116 -0.2690  

[74 rows x 16340 columns]

In [4]:
patientID = data['PATIENT_ID'] #train_clinical 데이터셋의 PATIENT_ID 열 추출

In [5]:
rnaID = rna.iloc[:, 2:] # 행 전체, 0,1번째 열 제외하고 출력
# 20531 rows * 2763 columns
rnaID = rnaID.dropna(axis=0) #NaN값 제거
# 16340 rows * 2763 columns
rnaID = rnaID.iloc[: , 12:]
#16340 rows * 2751 columns
rnaID = rnaID.transpose() #행/열 변환
#2751 rows * 16340 columns
rnaID.shape

(2751, 16340)

In [6]:
rnaID

1       2       3       4       6       11      12     \
TCGA-BR-6453-01 -0.3377  0.2974 -2.2844  0.5930 -1.1559  0.3951  0.0140   
TCGA-BR-6454-01 -0.1244  0.2972 -1.6241 -0.8885 -0.6654  3.9873 -0.6873   
TCGA-BR-6455-01  0.4916 -1.1981  0.0717 -0.0857 -1.2703 -1.3499 -1.0326   
TCGA-BR-6456-01 -0.7246 -0.8930 -1.9199 -0.1918 -1.0761 -0.2123 -1.5749   
TCGA-BR-6457-01 -1.3170 -0.6033 -1.4234 -0.4526 -0.7556 -0.4201  1.3878   
...                 ...     ...     ...     ...     ...     ...     ...   
TCGA-WY-A85A-01 -0.4623  0.2481 -0.4197  0.2058  0.4442  1.3310 -0.2275   
TCGA-WY-A85B-01  0.0507  0.5676 -0.2125  0.2314  0.6382 -1.6739  0.7388   
TCGA-WY-A85C-01  0.4778  0.4846 -0.5183 -0.6588  1.1459 -0.7668  0.4220   
TCGA-WY-A85D-01 -0.4763 -0.6968 -0.8822  0.4685  1.0834 -0.6127  1.5654   
TCGA-WY-A85E-01  0.2876 -0.9707 -0.0090  0.6967  1.7139  0.3330 -0.3630   

                  19      20      22     ...   20521   20522   20523   20524  \
TCGA-BR-6453-01 -0.7056 -0.5021 -0.0008  ... -1.2864 -0.2231 -0.4357 -0.6893   
TCGA-BR-6454-01  1.7188  0.0312  0.2824  ... -1.6461 -0.0658  1.6156  1.2233   
TCGA-BR-6455-01 -0.7076 -0.2781 -0.2199  ...  0.2030  1.4725 -1.5332 -4.0117   
TCGA-BR-6456-01  0.7257 -1.9996 -0.4320  ... -0.2636  0.2714  0.6561  0.2121   
TCGA-BR-6457-01  0.3657 -1.2008 -0.3903  ... -2.5712 -0.9814  0.8946  0.1286   
...                 ...     ...     ...  ...     ...     ...     ...     ...   
TCGA-WY-A85A-01  0.1635  0.7661 -0.8457  ... -0.5834 -0.4914 -0.3775 -0.6975   
TCGA-WY-A85B-01 -0.4172  0.9313 -1.3543  ...  1.0486  1.1282 -0.1515  0.5935   
TCGA-WY-A85C-01 -1.1259  0.7704 -0.6735  ... -0.6817 -0.7663  0.3284  0.7869   
TCGA-WY-A85D-01 -1.6966  0.3744  0.7605  ... -1.9247 -0.3125 -1.2386 -1.1186   
TCGA-WY-A85E-01 -1.3160  0.9403 -0.7307  ...  0.8830  1.1751 -0.3137 -0.3742   

                  20525   20526   20527   20528   20529   20530  
TCGA-BR-6453-01 -0.9083 -0.1498 -1.1634  0.2087  0.2361 -1.6824  
TCGA-BR-6454-01  0.0805 -1.4317 -1.2823 -1.0852 -0.4345 -1.1290  
TCGA-BR-6455-01 -0.4711  2.0172  0.5408 -0.2296 -0.7173  0.4233  
TCGA-BR-6456-01 -0.3215  0.1107  0.1492  2.3314 -0.5676 -0.8733  
TCGA-BR-6457-01 -0.4348 -1.4317 -0.0662  1.5187 -0.3325 -1.7130  
...                 ...     ...     ...     ...     ...     ...  
TCGA-WY-A85A-01  0.0466 -1.2143  0.4425 -0.9402 -0.1893  0.4236  
TCGA-WY-A85B-01  0.3402 -0.2231  0.3485 -0.8402  0.1042  1.0122  
TCGA-WY-A85C-01  0.9922  0.9422  1.0692 -0.4389  0.7413  1.2262  
TCGA-WY-A85D-01  0.6909 -1.2143 -0.1277 -0.6813 -0.5001  0.8035  
TCGA-WY-A85E-01 -2.4513  1.1519  0.7383 -0.3227 -0.4875  0.2730  

[2751 rows x 16340 columns]

In [7]:
rnaID = rnaID.rename(lambda label:label[:-3]) # 인덱스의 뒤부터 -3만큼 제외
# rnaID.shape

In [8]:
data = data.rename(index=data['PATIENT_ID']) #data의 인덱스를 PATIENT_ID로 선언

In [9]:
rna_pat_ID = list(rnaID.index) #rnaID 인덱스를 ran_pat_ID 로 리스트 타입 선언
patientID = list(data['PATIENT_ID'].values) # data의 columns중 PATIENT_ID의 값을 patientID로 리스트 타입 선언
# print(rna_pat_ID)

delete = []
for i in patientID: #patientID 리스트 만큼 반복함
    if i not in rna_pat_ID: # patientID의 I 값이 rna_pat_ID안에 들어있지않다면
        delete.append(i) # delete리스트에 I값을 추가함
data = data.drop(index=delete) # data의 인덱스 중 delete와 동일한 값을 drop시킴

delete = []
for i in rna_pat_ID: # rna_pat_ID 리스트 만큼 반복함
    if i not in patientID: # I값이 patientID 안에 들어있지않다면
        delete.append(i) # delete리스트에 I 값 추가
rnaID = rnaID.drop(index=delete) # rnaID의 인덱스 중 delete와 동일한 값을 drop함

rnaID.shape

(2595, 16340)

In [10]:
from iteration_utilities import duplicates

rna = list(rnaID.index) # rna에 rnaID의 인덱스 값을 리스트 형태로 저장 2595개
rna = list(duplicates(rna)) # rna에 중복되어 제거된 값을 리스트 형태로 저장 ['TCGA-ER-A19T', 'TCGA-ER-A2NF']

In [11]:
rna

['TCGA-ER-A19T', 'TCGA-ER-A2NF']

In [12]:
rnaID = rnaID.drop(index=rna) # rnaID 인덱스 중 rna리스트안에 있는 값과 일치하는값을 drop함
rnaID.shape # (2591,16340)

(2591, 16340)

In [13]:
delete = []
t1 = list(rnaID.index) # t1에 rnaID 인덱스 값을 리스트로 생성 rnaID 2591개의 rows값
t2 = list(data.index) # t2에 data의 인덱스 값을 리스트로 생성 data 2593개의 rows값

for i in t1: # t1만큼 반복함
    if i not in t2: # i값이 t2에 없으면 
        delete.append(i) # delete 리스트의 i값 추가
        
data = data.drop(index=delete) # data안에 delete 리스트 값을 drop함
rnaID.shape
# data.shape

(2591, 16340)

In [14]:
data_du = list(data['PATIENT_ID']) # data_du 리스트에 data의 PATIENT_ID값 리스트로 생성
data_du = list(duplicates(data_du)) # data_du 중복되어 제거된 값을 리스트 형태로 저장

data = data.drop(index=data_du)
rnaID.shape

(2591, 16340)

In [15]:
rna_pat_ID = list(rnaID.index) # rna_pat_ID 에 rnaID 인덱스 값 리스트로 생성
patientID = list(data['PATIENT_ID'].values) # data의 PATIENT_ID 칼럼의 값을 patientID리스트로 생성
# print(rna_pat_ID)

delete = []
for i in patientID:
    if i not in rna_pat_ID:
        delete.append(i)
data = data.drop(index=delete)

delete = []
for i in rna_pat_ID:
    if i not in patientID:
        delete.append(i)
rnaID = rnaID.drop(index=delete)
rnaID.shape
print(data)

                PATIENT_ID CANCER_TYPE_ACRONYM  \
TCGA-BR-4191  TCGA-BR-4191                STAD   
TCGA-BR-4201  TCGA-BR-4201                STAD   
TCGA-BR-4253  TCGA-BR-4253                STAD   
TCGA-BR-4267  TCGA-BR-4267                STAD   
TCGA-BR-4279  TCGA-BR-4279                STAD   
...                    ...                 ...   
TCGA-WY-A85B  TCGA-WY-A85B                 LGG   
TCGA-WY-A85C  TCGA-WY-A85C                 LGG   
TCGA-WY-A85D  TCGA-WY-A85D                 LGG   
TCGA-WY-A85E  TCGA-WY-A85E                 LGG   
TCGA-R8-A6YH  TCGA-R8-A6YH                 LGG   

                                  OTHER_PATIENT_ID   AGE     SEX  \
TCGA-BR-4191  74f859cf-6df5-4e96-ae6b-cfaab691d5fd  72.0    Male   
TCGA-BR-4201  8520654b-2192-46cf-9d72-1ddb885a7c55  66.0  Female   
TCGA-BR-4253  411257a4-a148-4606-8c8b-f9f1240e40ed  80.0  Female   
TCGA-BR-4267  0d0f0200-25b8-483b-b04a-82a7833b4d30  51.0    Male   
TCGA-BR-4279  117eb38b-0c62-4336-a866-fa5bd013256a  43.0   

In [16]:
cancer = data['CANCER_TYPE_ACRONYM']
rnaID.shape #(2591, 16340)
# cancer.shape #(2591,)
cancer

TCGA-BR-4191    STAD
TCGA-BR-4201    STAD
TCGA-BR-4253    STAD
TCGA-BR-4267    STAD
TCGA-BR-4279    STAD
                ... 
TCGA-WY-A85B     LGG
TCGA-WY-A85C     LGG
TCGA-WY-A85D     LGG
TCGA-WY-A85E     LGG
TCGA-R8-A6YH     LGG
Name: CANCER_TYPE_ACRONYM, Length: 2591, dtype: object

In [25]:
X = rnaID
Y = cancer.values
print(type(X))
print('*' *20)
print(type(Y))

<class 'pandas.core.frame.DataFrame'>
********************
<class 'numpy.ndarray'>


In [24]:
X = X.iloc[:, 0:16340]
X.shape #(2591, 10000)
test = test.iloc[:, 0:16340]
# test # 74 rows * 10000 columns
print(type(test))

<class 'pandas.core.frame.DataFrame'>


In [27]:
from sklearn.preprocessing import RobustScaler
RC = RobustScaler()
# X = RC.fit_transform(X)
# test = RC.fit_transform(test)

from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X = sc.fit_transform(X)
test = sc.fit_transform(test)


from sklearn.feature_selection import VarianceThreshold
selector = VarianceThreshold(1e-5)
X = selector.fit_transform(X)
test = selector.transform(test)




In [28]:
test

array([[0.02183301, 0.31115769, 0.48086697, ..., 0.77118719, 0.52679358,
        0.61526995],
       [0.69348094, 0.76787396, 0.49875124, ..., 0.55382119, 0.54521875,
        0.67899567],
       [0.75532972, 0.62584778, 0.67368182, ..., 0.59541069, 0.84887932,
        0.84481607],
       ...,
       [0.11500891, 0.51745008, 0.59573502, ..., 0.51674692, 0.27579035,
        0.67972547],
       [0.25603236, 0.39977393, 0.        , ..., 0.72862762, 0.43165802,
        0.20786944],
       [0.52592885, 0.22444894, 0.44267077, ..., 0.60996173, 0.48686014,
        0.635751  ]])

In [27]:
Y

array(['STAD', 'STAD', 'STAD', ..., 'LGG', 'LGG', 'LGG'], dtype=object)

In [28]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

encoder.fit(Y)
Y_encoded = encoder.transform(Y)

for label in np.unique(Y):
    if label not in encoder.classes_: 
        encoder.classes_ = np.append(encoder.classes_, label)
Y_encoded = encoder.transform(Y)

In [30]:
Y

array(['STAD', 'STAD', 'STAD', ..., 'LGG', 'LGG', 'LGG'], dtype=object)

In [29]:
print(encoder.classes_)
print(Y_encoded)

['COAD' 'LGG' 'LIHC' 'LUAD' 'SKCM' 'STAD']
[5 5 5 ... 1 1 1]


In [23]:
test

array([[0.02183301, 0.31115769, 0.48086697, ..., 0.77118719, 0.52679358,
        0.61526995],
       [0.69348094, 0.76787396, 0.49875124, ..., 0.55382119, 0.54521875,
        0.67899567],
       [0.75532972, 0.62584778, 0.67368182, ..., 0.59541069, 0.84887932,
        0.84481607],
       ...,
       [0.11500891, 0.51745008, 0.59573502, ..., 0.51674692, 0.27579035,
        0.67972547],
       [0.25603236, 0.39977393, 0.        , ..., 0.72862762, 0.43165802,
        0.20786944],
       [0.52592885, 0.22444894, 0.44267077, ..., 0.60996173, 0.48686014,
        0.635751  ]])

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

In [25]:
print(X.shape)
print(Y.shape)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)
print(test.shape)

(2591, 16340)
(2591,)
(2072, 16340)
(519, 16340)
(2072,)
(519,)
(74, 16340)


In [26]:
X

array([[0.48863336, 0.47320374, 0.27447469, ..., 0.64573835, 0.60790836,
        0.37120168],
       [0.51832723, 0.47318455, 0.33873809, ..., 0.52703955, 0.52178715,
        0.41632084],
       [0.60408169, 0.32964723, 0.50378106, ..., 0.60552992, 0.48546881,
        0.54288114],
       ...,
       [0.60216057, 0.49117351, 0.44635958, ..., 0.58632932, 0.67278822,
        0.60834223],
       [0.4693386 , 0.37776818, 0.41094317, ..., 0.56409221, 0.51336253,
        0.57387916],
       [0.57568249, 0.35147588, 0.49592697, ..., 0.59698918, 0.51498067,
        0.53062705]])

In [27]:
Y

array(['STAD', 'STAD', 'STAD', ..., 'LGG', 'LGG', 'LGG'], dtype=object)

In [28]:
test

array([[0.02183301, 0.31115769, 0.48086697, ..., 0.77118719, 0.52679358,
        0.61526995],
       [0.69348094, 0.76787396, 0.49875124, ..., 0.55382119, 0.54521875,
        0.67899567],
       [0.75532972, 0.62584778, 0.67368182, ..., 0.59541069, 0.84887932,
        0.84481607],
       ...,
       [0.11500891, 0.51745008, 0.59573502, ..., 0.51674692, 0.27579035,
        0.67972547],
       [0.25603236, 0.39977393, 0.        , ..., 0.72862762, 0.43165802,
        0.20786944],
       [0.52592885, 0.22444894, 0.44267077, ..., 0.60996173, 0.48686014,
        0.635751  ]])

In [29]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=3000, min_samples_split=400, min_samples_leaf=100)

classifier.fit(X_train, Y_train)
score = classifier.score(X_test, Y_test)
print(score)

0.9961464354527938


In [30]:
pred = classifier.predict(test)
pred

array(['STAD', 'LUAD', 'LIHC', 'LIHC', 'STAD', 'LIHC', 'STAD', 'STAD',
       'STAD', 'LUAD', 'LUAD', 'LUAD', 'SKCM', 'SKCM', 'LUAD', 'COAD',
       'LUAD', 'STAD', 'LUAD', 'LUAD', 'LIHC', 'LUAD', 'LUAD', 'LIHC',
       'LUAD', 'LIHC', 'LIHC', 'LGG', 'LIHC', 'LIHC', 'COAD', 'LIHC',
       'LIHC', 'STAD', 'STAD', 'LIHC', 'COAD', 'COAD', 'COAD', 'COAD',
       'LUAD', 'COAD', 'LGG', 'SKCM', 'LUAD', 'COAD', 'COAD', 'LGG',
       'LGG', 'SKCM', 'LGG', 'LGG', 'LGG', 'LGG', 'LIHC', 'COAD', 'LGG',
       'LGG', 'LGG', 'COAD', 'LGG', 'SKCM', 'SKCM', 'SKCM', 'STAD',
       'SKCM', 'SKCM', 'LGG', 'LUAD', 'SKCM', 'SKCM', 'LGG', 'SKCM',
       'SKCM'], dtype=object)

In [31]:
# pred= encoder.inverse_transform(pred)
# pred

In [32]:
# from sklearn.naive_bayes import BernoulliNB
# from sklearn.metrics import accuracy_score

# model = BernoulliNB()
# model.fit(X_train, Y_train)
# print("train accuracy:{:5.3f}".format(accuracy_score(Y_train, model.predict(X_train))))
# print("test accuracy :{:5.3f}".format(accuracy_score(Y_test, model.predict(X_test))))
# pred = model.predict(test)

In [33]:
pred

array(['STAD', 'LUAD', 'LIHC', 'LIHC', 'STAD', 'LIHC', 'STAD', 'STAD',
       'STAD', 'LUAD', 'LUAD', 'LUAD', 'SKCM', 'SKCM', 'LUAD', 'COAD',
       'LUAD', 'STAD', 'LUAD', 'LUAD', 'LIHC', 'LUAD', 'LUAD', 'LIHC',
       'LUAD', 'LIHC', 'LIHC', 'LGG', 'LIHC', 'LIHC', 'COAD', 'LIHC',
       'LIHC', 'STAD', 'STAD', 'LIHC', 'COAD', 'COAD', 'COAD', 'COAD',
       'LUAD', 'COAD', 'LGG', 'SKCM', 'LUAD', 'COAD', 'COAD', 'LGG',
       'LGG', 'SKCM', 'LGG', 'LGG', 'LGG', 'LGG', 'LIHC', 'COAD', 'LGG',
       'LGG', 'LGG', 'COAD', 'LGG', 'SKCM', 'SKCM', 'SKCM', 'STAD',
       'SKCM', 'SKCM', 'LGG', 'LUAD', 'SKCM', 'SKCM', 'LGG', 'SKCM',
       'SKCM'], dtype=object)

In [34]:
print(test.shape)
print(X_test.shape)

(74, 16340)
(519, 16340)


In [35]:
submission = pd.read_csv('sample_submission.csv')
submission = submission.drop(['expected'], axis=1)
submission['expected'] = pred
submission.to_csv('RF_Result.csv', index = False)

In [36]:
pred

array(['STAD', 'LUAD', 'LIHC', 'LIHC', 'STAD', 'LIHC', 'STAD', 'STAD',
       'STAD', 'LUAD', 'LUAD', 'LUAD', 'SKCM', 'SKCM', 'LUAD', 'COAD',
       'LUAD', 'STAD', 'LUAD', 'LUAD', 'LIHC', 'LUAD', 'LUAD', 'LIHC',
       'LUAD', 'LIHC', 'LIHC', 'LGG', 'LIHC', 'LIHC', 'COAD', 'LIHC',
       'LIHC', 'STAD', 'STAD', 'LIHC', 'COAD', 'COAD', 'COAD', 'COAD',
       'LUAD', 'COAD', 'LGG', 'SKCM', 'LUAD', 'COAD', 'COAD', 'LGG',
       'LGG', 'SKCM', 'LGG', 'LGG', 'LGG', 'LGG', 'LIHC', 'COAD', 'LGG',
       'LGG', 'LGG', 'COAD', 'LGG', 'SKCM', 'SKCM', 'SKCM', 'STAD',
       'SKCM', 'SKCM', 'LGG', 'LUAD', 'SKCM', 'SKCM', 'LGG', 'SKCM',
       'SKCM'], dtype=object)